blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/cataclysmbnteam/Cataclysm-BN/discussions/
    about: Questions, simple suggestions, porting DDA features, and more.
  - name: Official Discord
    url: https://discord.gg/B5q4XCa
    about: Get involved with devs and players!
