name: Windows build (CMake + MSYS2)

on:
  push:
    branches:
    - upload
    paths-ignore:
    - 'android/**'
    - 'build-data/osx/**'
    - 'doc/**'
    - 'doxygen_doc/**'
    - 'gfx/**'
    - 'lang/**'
    - 'tools/**'
    - '!tools/format/**'
    - 'utilities/**'
    - 'scripts/**'

# We only care about the latest revision, so cancel previous instances.
concurrency:
  group: msys2-cmake-build-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build_catatclysm:
    name: Build
    runs-on: windows-2019
    if: github.event.pull_request.draft == false

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup MSYS2
      # Will by default install MINGW64
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: |
          git
          make
          gettext
          mingw-w64-x86_64-libmad
          mingw-w64-x86_64-libwebp
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_image
          mingw-w64-x86_64-SDL2_mixer
          mingw-w64-x86_64-SDL2_ttf
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake

    - name: Create build directory
      run: mkdir build

    - name: Configure
      run: |
        cd build
        cmake.exe \
          -DTILES=ON \
          -DSOUND=ON \
          -DLUA=ON \
          -DTESTS=ON \
          -DDYNAMIC_LINKING=ON \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_CXX_FLAGS="-w" \
          -G "Ninja" \
          ..

    - name: Build
      run: |
        cmake.exe --build build -j$((`nproc`+0))

    - name: Compile translations
      run: |
        cmake.exe --build build --target translations_compile

    - name: Run tests
      run: |
          ./build/tests/cata_test-tiles.exe --rng-seed time
